"""Auto generate tables

Revision ID: ae946964035d
Revises: 
Create Date: 2019-12-13 00:39:52.289861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae946964035d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('casting_time', sa.String(length=255), nullable=True),
    sa.Column('range', sa.String(length=100), nullable=True),
    sa.Column('components', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_spell',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'class_id')
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'spell_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('class_spell')
    op.drop_table('users')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
